project:
  type: website
  output-dir: docs

website:
  title: "Data Visualization"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hquin20/Data334_Blog
      - icon: linkedin
        href: https://www.linkedin.com/in/hailey-quintavalle-b8071221b/
format:
  html:
    theme: slate
    css: styles.css



